
###
GET http://localhost:8080/book/get/PkMju2oBd2QFj63oa1sE
Content-Type: application/json

{}

###
POST http://localhost:8080/book/add
Content-Type: application/json

{
  "type": "IT",
  "wordCount": 90000,
  "author": "小伦",
  "title": "跟Z开始学ES",
  "publishDate": "2019-05-15 16:56:20"
}

###
POST http://localhost:8080/book/update
Content-Type: application/json

{
  "id": "PkMju2oBd2QFj63oa1sE",
  "type": "IT",
  "wordCount": 8978,
  "author": "小伦伦",
  "title": "小伦的ES文章",
  "publishDate": "2019-05-15 19:29:14"
}

###
GET http://localhost:8080/book/delete/PkMju2oBd2QFj63oa1sE
Content-Type: application/json

{}

###
POST http://localhost:8080/book/bool
Content-Type: application/json

{
  "author": "张翠山"
}

###
