server:
  port: 8502
spring:
  application:
    name: spring-cloud-consul-producer-2
  cloud:
    consul:
      host: 47.99.200.185
      port: 8500
      discovery:
        service-name: server-producer
        health-check-url: http://10.247.18.152:8502/actuator/health